// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";

const lovableAuth = createLovableAuth();

export const lovable = {
  auth: {
    signInWithOAuth: (provider: string, options: { redirect_uri: string }) =>
      lovableAuth.signInWithOAuth(provider, options),
  },
};
